---
- name: Deploy Web Application
  hosts: all
  become: yes
  tasks:
  - name: Running apt update
    apt: update_cache=yes
  - name: Installing required packages
    apt: name={{item}} state=present
    with_items:
     - git
     - python-pip
     - uwsgi
     - uwsgi-plugin-python
     - nginx
  - name: Clone web app repository into /opt
    git:
      repo: https://github.com/pim-zwiers/Sentia-Assessment-1.git
      version: master
      dest: /opt/webapp
      accept_hostkey: yes
    become: yes
  - name: Move nginx config file
    synchronize:
      src: /opt/webapp/WebApp/Config/nginx.conf
      dest: /etc/nginx/sites-enabled/website
    register: nginx_config
  - name: nginx restart
    service: name=nginx state=restarted
    when: nginx_config.changed
  - name: Install Python dependencies
    pip:
      requirements: requirements.txt
      chdir: /opt/webapp/WebApp
  - name: Run Web Application
    command: python /opt/webapp/WebApp/website.py &
    become: yes