---
- name: Deploy Web Application
  hosts: all
  become: yes
  tasks:
  - name: Running apt update
    apt: update_cache=yes
  - name: Installing required packages
    apt: 
      name: ['git','python3-pip','python3-dev','python3-venv','python-setuptools','nginx']
      state: present
  - name: Install virtualenv pip package
    pip:
      name: virtualenv
      executable: pip3
  - name: Clone web app repository into /home/sentia/webapp
    git:
      repo: https://github.com/pim-zwiers/Sentia-Assessment-1.git
      version: master
      dest: /home/sentia/webapp
      accept_hostkey: yes
    become: no
  - name: Replace storage account name
    replace:
      path: /home/sentia/webapp/src/config/sentiawebapp.service
      regexp: 'storage_name'
      replace: "{{ lookup('env','STORAGE_ACCOUNT_NAME') }}"
  - name: Replace storage account key
    replace:
      path: /home/sentia/webapp/src/config/sentiawebapp.service
      regexp: 'storage_key'
      replace: "{{ lookup('env','STORAGE_ACCOUNT_KEY') }}"
  - name: Copy systemd service to services
    copy:
      src: /home/sentia/webapp/src/config/sentiawebapp.service
      dest: /etc/systemd/system/sentiawebapp.service
      remote_src: yes
    become: yes
  - name: Copy nginx config
    copy:
      src: /home/sentia/webapp/src/config/nginx.conf
      dest: /etc/nginx/sites-available/sentiawebapp
      remote_src: yes
  - name: Link nginx config to sites-enabled
    file:
      src: /etc/nginx/sites-available/sentiawebapp
      dest: /etc/nginx/sites-enabled/sentiawebapp
      owner: sentia
      group: www-data
      state: link
  - name: Remove default nginx sites
    file:
      path: /etc/nginx/sites-available/default
      state: absent
  - name: Remove default nginx sites
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: restart nginx
    service:
      name: nginx
      state: restarted
  - name: Install requirements
    pip: 
      requirements: /home/sentia/webapp/src/requirements.txt
      virtualenv: /home/sentia/webapp/web-venv
      virtualenv_python: python3.6
  - name: start sentiawebapp
    service:
      name: sentiawebapp
      state: started
  - name: restart nginx
    service:
      name: nginx
      state: restarted
