---
- name: Deploy Web Application
  hosts: all
  become: yes
  tasks:
  - name: Running apt update
    apt: update_cache=yes
  - name: Installing required packages
    apt: name={{item}} state=present
    with_items:
     - git
     - python3-pip
     - python3-dev
     - python3-venv
     - nginx
  - name: Clone web app repository into /home/pimzwiers/sentia
    git:
      repo: https://github.com/pim-zwiers/Sentia-Assessment-1.git
      version: master
      dest: /home/pimzwiers/sentia
      accept_hostkey: yes
    become: no
  - name: Copy systemd service to services
    copy:
      src: /home/pimzwiers/sentia/src/config/sentiawebapp.service
      dest: /etc/systemd/system/sentiawebapp.service
      remote_src: yes
    become: yes
  - name: Copy nginx config
    copy:
      src: /home/pimzwiers/sentia/src/config/nginx.conf
      dest: /etc/nginx/sites-available/sentiawebapp
      remote_src: yes
  - name: Link nginx config to sites-enabled
    file:
      src: /etc/nginx/sites-available/sentiawebapp
      dest: /etc/nginx/sites-enabled/sentiawebapp
      owner: pimzwiers
      group: www-data
      state: link
  - name: Remove default nginx sites
    file:
      src: /etc/nginx/sites-available/default
      state: absent
  - name: Remove default nginx sites
    file:
      src: /etc/nginx/sites-enabled/default
      state: absent
  - name: restart nginx
    service:
      name: nginx
      state: restarted
  - name: Install requirements
    pip: 
      requirements: /home/pimzwiers/sentia/src/requirements.txt
      virtualenv: /home/pimzwiers/sentia/web-venv
      virtualenv_python: python3.6
  - name: start sentiawebapp
    service:
      name: sentiawebapp
      state: started
  - name: restart nginx
    service:
      name: nginx
      state: restarted
